name = "route-v2"
main = "route-v2-worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "subway-db"
database_id = "c06de2e6-d6bc-401c-be32-25fde0b5f747"

[[services]]
binding = "BUSAPI"
service = "gentle-lab-7e47subway-api"

[[kv_namespaces]]
binding = "ROWS_KV"
id = "dc7124fce2d946768165f47fc58d6b7e"
